version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app 
    command: sh -c "cd homepage && npm run dev"
    ports:
      - "3000:3000"
    restart: always
    environment:
        - CHOKIDAR_USEPOLLING=true